export const Theme = {
    message: {
        font: "'Saira', sans-serif",
        fontSize: "0.9rem",
        fontWeight: "bold",
        color: "white",
        lineHeight: "1.5",
        letterSpacing: "2px",
        padding: "1rem",
        background: "#424242",
    },
    headers: {
        h1: {
            font: "'DEBUG', sans-serif;",
            fontSize: "4rem",
            fontWeight: "bold",
            color: "whitesmoke",
            span: "#d3eca7",
            lineHeight: "1.5",
            letterSpacing: "5px",
            padding: "1rem",
        },
        h2: {
            backgroundColor: "yellow",
            font: "'Saira', sans-serif",
            fontSize: "2rem",
            fontWeight: "regular",
            color: "white",
            lineHeight: "1.5",
            letterSpacing: "1px",
            padding: "0.8rem",
        },
        h3: {
            font: "'Saira', sans-serif",
            fontSize: "0.8rem",
            fontWeight: "regular",
            color: "white",
            lineHeight: "1.5",
            letterSpacing: "1px",
            padding: "0.8rem",
        },
    },
    buttons: {},
    background: {
        primary: "#212121",
        secondary: "#424242",
        stage: "black",
        fillCol: "#46b3e6",
    },
    border: {
        stage: "#424242",
        avatar: "#b33030",
    },
};
